services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    image: aterreno/sci-calc-api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - addition-service
      - subtraction-service
      - multiplication-service
      - division-service
      - power-service
      - square-root-service
      - log-service
      - trig-service
      - memory-service
      - factorial-service
      - conversion-service
      - matrix-service
      - bitwise-service
      - complex-service
      - otel-collector
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=api-gateway
    networks:
      - calc-network

  # Rust Addition Service
  addition-service:
    build: ./services/addition-service-rust
    image: aterreno/sci-calc-addition-service
    ports:
      - "8001:8001"
    networks:
      - calc-network

  # Go Subtraction Service
  subtraction-service:
    build: ./services/subtraction-service-go
    image: aterreno/sci-calc-subtraction-service
    ports:
      - "8002:8002"
    networks:
      - calc-network

  # Python Multiplication Service
  multiplication-service:
    build: ./services/multiplication-service-python
    image: aterreno/sci-calc-multiplication-service
    ports:
      - "8003:8003"
    networks:
      - calc-network

  # Ruby Division Service
  division-service:
    build: ./services/division-service-ruby
    image: aterreno/sci-calc-division-service
    ports:
      - "8004:8004"
    networks:
      - calc-network

  # Java Power Service
  power-service:
    build: ./services/power-service-java
    image: aterreno/sci-calc-power-service
    ports:
      - "8005:8005"
    networks:
      - calc-network

  # F# Square Root Service
  square-root-service:
    build: ./services/square-root-service-fsharp
    image: aterreno/sci-calc-square-root-service
    ports:
      - "8006:8006"
    networks:
      - calc-network

  # PHP Logarithm Service
  log-service:
    build: ./services/log-service-php
    image: aterreno/sci-calc-log-service
    ports:
      - "8007:8007"
    networks:
      - calc-network

  # Kotlin Trigonometry Service
  trig-service:
    build: ./services/trig-service-kotlin
    image: aterreno/sci-calc-trig-service
    ports:
      - "8008:8008"
    networks:
      - calc-network

  # C# Memory Service
  memory-service:
    build: ./services/memory-service-csharp
    image: aterreno/sci-calc-memory-service
    ports:
      - "8009:8009"
    networks:
      - calc-network

  # Elixir Factorial Service
  factorial-service:
    build: ./services/factorial-service-elixir
    image: aterreno/sci-calc-factorial-service
    ports:
      - "8010:8010"
    networks:
      - calc-network


  # TypeScript Conversion Service
  conversion-service:
    build: ./services/conversion-service-typescript
    image: aterreno/sci-calc-conversion-service
    ports:
      - "8012:8012"
    networks:
      - calc-network

  # Julia Matrix Service
  matrix-service:
    build: ./services/matrix-service-julia
    image: aterreno/sci-calc-matrix-service
    ports:
      - "8014:8014"
    networks:
      - calc-network

  # Swift Bitwise Service
  bitwise-service:
    build: ./services/bitwise-service-swift
    image: aterreno/sci-calc-bitwise-service
    ports:
      - "8016:8016"
    networks:
      - calc-network

  # Clojure Complex Numbers Service
  complex-service:
    build: ./services/complex-service-clojure
    image: aterreno/sci-calc-complex-service
    ports:
      - "8017:8017"
    networks:
      - calc-network

  # Frontend service
  frontend:
    build: ./frontend
    image: aterreno/sci-calc-frontend
    ports:
      - "3001:3001"
    depends_on:
      - api-gateway
    networks:
      - calc-network
      
  # Telemetry services    
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./telemetry/otel-config.yaml:/etc/otel/config.yaml
      - ./telemetry/logs:/var/logs 
    command: ["--config", "/etc/otel/config.yaml"]
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - jaeger
      - prometheus
      - loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./telemetry/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - ./telemetry/logs:/var/logs  # ✅ Mount logs directory
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - loki


  # Jaeger for tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # UI
      - "14268:14268"  # Collector
      - "14250:14250"
      - "6831:6831/udp"

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Loki for logs
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  # Blackbox Exporter for uptime monitoring
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./telemetry/blackbox.yml:/etc/blackbox_exporter/config.yml

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./telemetry/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./telemetry/grafana/dashboards:/var/lib/grafana/dashboards  
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      # - GF_SERVER_HTTP_PORT=6000
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  calc-network:
    driver: bridge