receivers:
  otlp:
    protocols:
      http:
        include_metadata: true
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - http://*
            - https://*
      grpc:

processors:
  batch: {}

exporters:
  otlphttp:
    endpoint: "http://jaeger:4318/v1/traces"  # Send traces to Jaeger

  prometheus:
    endpoint: "0.0.0.0:9090"  # Prometheus metrics

  file:
    path: "/var/logs/otel-collector.log"  # Logs stored in a file

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]  # Store logs in a file
