name: CI for Power Service (Java)

on:
  push:
    paths:
      - 'services/power-service-java/**'
  pull_request:
    paths:
      - 'services/power-service-java/**'

jobs:
  test-and-build:
    name: Test and Build Power Service (Java)
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Run the tests
      - name: Run Tests
        working-directory: ./services/power-service-java
        run: ./run.sh test

      # Build Docker image if tests pass
      - name: Build Docker Image
        working-directory: ./services/power-service-java
        run: |
          docker build -t power-service-java:latest .