name: CI for Square Root Service (F#)

on:
  push:
    paths:
      - 'services/square-root-service-fsharp/**'
  pull_request:
    paths:
      - 'services/square-root-service-fsharp/**'

jobs:
  test-and-build:
    name: Test and Build Square Root Service (F#)
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Run the tests
      - name: Run Tests
        working-directory: ./services/square-root-service-fsharp
        run: ./run.sh test

      # Build Docker image if tests pass
      - name: Build Docker Image
        working-directory: ./services/square-root-service-fsharp
        run: |
          docker build -t square-root-service-fsharp:latest .