name: CI for Trig Service (Kotlin)

on:
  push:
    paths:
      - 'services/trig-service-kotlin/**'
  pull_request:
    paths:
      - 'services/trig-service-kotlin/**'

jobs:
  test-and-build:
    name: Test and Build Trig Service (Kotlin)
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Run the tests
      - name: Run Tests
        working-directory: ./services/trig-service-kotlin
        run: ./run.sh test

      # Build Docker image if tests pass
      - name: Build Docker Image
        working-directory: ./services/trig-service-kotlin
        run: |
          docker build -t trig-service-kotlin:latest .